const mongoose = require("mongoose");

const UtilizationSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  center_id: { type: mongoose.Schema.Types.ObjectId, ref: "centers" },
  centerName: String,
  approvalDate: String,
  approvalNo: String,
  voucherDate: String,
  voucherNumber: String,
  program_id: { type: mongoose.Schema.Types.ObjectId, ref: "programs" },
  program: String,
  project_id: { type: mongoose.Schema.Types.ObjectId, ref: "projects" },
  project: String,
  activityName_id: { type: mongoose.Schema.Types.ObjectId, ref: "activities" },
  activityName: String,
  subactivityName_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "subactivities",
  },
  subactivityName: String,
  unit: String,
  unitCost: Number,
  quantity: Number,
  totalCost: Number,
  sourceofFund: {
    LHWRF: Number,
    grant: Number,
    CC: Number,
  },
  convergence: Number,
  noOfHouseholds: Number,
  noOfBeneficiaries: Number,
  status: String,
  convergenceAgencyName: String,
  convergenceDocumentName: String,
  activityStatus: String,
  convergenceNote: String,
  fileName: String,
  // documentUrl: Array,
  // documentName: Array,
  voucherDocumentUrl: String,
  voucherDocumentName: String,
  convergenceDocumentUrl: String,
  S3ConvergenceDocumentName: String,
  finalStatus: String,
  paymentDetails: {
    UTRNumber: String,
    paymentDate: String,
    paymentStatus: String,
    updatedByName: String,
    updatedByRole: String,
    updatedAt: Date,
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
  },
  approvalAuthourities: [
    {
      approvalLevel: String,
      approvalAuthRole: String,
      approvalAuthName: String,
      approvalAuthMobile: String,
      approvalAuthEmail: String,
      status: String,
      remark: String,
      updatedAt: Date,
      updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
    },
  ],
  uploadTime: Date,
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
  createdAt: Date,
  updateLog: [
    {
      updatedAt: Date,
      updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
    },
  ],
});
module.exports = mongoose.model("utilizationdetails", UtilizationSchema);
