const mongoose = require("mongoose");

const ApprovalSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  plan_id: { type: mongoose.Schema.Types.ObjectId, ref: "annualplans" },
  center_id: { type: mongoose.Schema.Types.ObjectId, ref: "centers" },
  centerName: String,
  approvalSubmissionDate: String,
  approvalDate: String,
  approvalNo: String,
  program_id: { type: mongoose.Schema.Types.ObjectId, ref: "programs" },
  program: String,
  project_id: { type: mongoose.Schema.Types.ObjectId, ref: "projects" },
  project: String,
  activityName_id: { type: mongoose.Schema.Types.ObjectId, ref: "activities" },
  activityName: String,
  subactivityName_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "subactivities",
  },
  subactivityName: String,
  unit: String,
  unitCost: Number,
  quantity: Number,
  noOfHouseholds: Number,
  noOfBeneficiaries: Number,
  totalCost: Number,
  sourceofFund: {
    LHWRF: Number,
    grant: Number,
    CC: Number,
  },
  convergence: Number,
  remarks: String,
  fileName: String,
  documentUrl: Array,
  documentName: Array,
  utilizationStatus: String,
  finalStatus: String,
  approvalAuthourities: [
    {
      approvalLevel: String,
      approvalAuthRole: String,
      approvalAuthName: String,
      approvalAuthMobile: String,
      approvalAuthEmail: String,
      status: String,
      remark: String,
      updatedAt: Date,
      updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
    },
  ],
  uploadTime: Date,
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
  createdAt: Date,
  updateLog: [
    {
      updatedAt: Date,
      updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "users" },
    },
  ],
});
module.exports = mongoose.model("approvalDetails", ApprovalSchema);
